alias: Dishwasher ON (MKIT)
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ states('input_number.theshold') | int < states('sensor.fv_overall') |
      int }}
condition: []
action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.dish
mode: single



alias: Dish OFF (MKIT)
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ states('input_number.theshold') | int > states('sensor.fv_overall') |
      int }}
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.dish
mode: single
